function C1 = C1Func(in1)
%C1FUNC
%    C1 = C1FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Jul-2018 11:38:52

yddot = in1(:,7);
zddot = in1(:,8);
t2 = sqrt(2.0);
C1 = t2.*yddot.*(1.0./2.0)-t2.*zddot.*(1.0./2.0);
