function C2 = C2Func(in1)
%C2FUNC
%    C2 = C2FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Jul-2018 11:52:05

Tddot = in1(:,9);
yddot = in1(:,7);
C2 = -Tddot-yddot;
