function C2 = C2Func(in1)
%C2FUNC
%    C2 = C2FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Jul-2018 11:38:52

Tddot = in1(:,9);
yddot = in1(:,7);
zddot = in1(:,8);
t2 = sqrt(2.0);
C2 = -Tddot-t2.*yddot.*(1.0./2.0)-t2.*zddot.*(1.0./2.0);
