function C3 = C3Func(in1)
%C3FUNC
%    C3 = C3FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Jul-2018 10:14:55

w1dot = in1(13,:);
w2dot = in1(14,:);
w3dot = in1(15,:);
x = in1(1,:);
xddot = in1(10,:);
y = in1(2,:);
zddot = in1(12,:);
t2 = x.^2;
t3 = t2.*(1.0./2.0);
t4 = y.^2;
t5 = t4.*(1.0./2.0);
t6 = t3+t5;
t7 = cos(t6);
t8 = abs(t7);
t9 = 1.0./t8.^2;
t10 = abs(x);
t11 = 1.0./t10.^2;
t12 = t9.*t11;
t13 = t12+1.0;
t14 = 1.0./sqrt(t13);
t15 = t7.^2;
t16 = t2.*t15;
t17 = t4.*t15;
t18 = t16+t17+1.0;
t19 = 1.0./sqrt(t18);
t20 = 1.0./x;
t21 = 1.0./t7;
C3 = -t14.*zddot+t14.*(t7.*t19.*w2dot.*x.*(1.0./1.0e1)-t7.*t19.*w3dot.*y.*(1.0./1.0e1))-t14.*t20.*t21.*xddot+t14.*t20.*t21.*(t19.*w2dot.*(1.0./1.0e1)+t7.*t19.*w1dot.*y.*(1.0./1.0e1));
