function N_lam = N_lamFunc(y)
%N_LAMFUNC
%    N_LAM = N_LAMFUNC(Y)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Jul-2018 11:38:51

t2 = sqrt(2.0);
t3 = t2.*(1.0./2.0);
N_lam = [0.0;t3;t3];
