function N_n = N_nFunc(y)
%N_NFUNC
%    N_N = N_NFUNC(Y)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Jul-2018 11:38:51

t2 = sqrt(2.0);
N_n = [0.0;t2.*(-1.0./2.0);t2.*(1.0./2.0)];
