function Sddot = SddotFunc(in1)
%SDDOTFUNC
%    SDDOT = SDDOTFUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Jul-2018 11:52:05

Sddot = [1.0./2.0;0.0;-1.0./2.0;9.81e2./1.0e2;1.0./2.0];
