function Sddot = SddotFunc(in1)
%SDDOTFUNC
%    SDDOT = SDDOTFUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Jul-2018 11:38:51

t2 = sqrt(2.0);
t3 = t2.*(7.0./4.0);
t4 = t3-9.81e2./4.0e2;
t5 = t2.*(9.81e2./4.0e2);
Sddot = [t4;t4;t5-7.0./2.0;t2.*(9.81e2./2.0e2);t5+7.0./2.0];
